// packages/app/components/login-dialog.tsx
import Button from 'react-bootstrap/Button'
import Modal from 'react-bootstrap/Modal'
import { MdPerson } from 'react-icons/md'
import styles from './login-dialog.module.css'

const LoginDialog = ({ show = false, onHide = () => {} }) => {
    function login() {
        window.location.href = process.env.NEXT_PUBLIC_API_BASE_PATH + '/login'
    }

    return (
        <Modal
            show={show}
            centered
            onHide={onHide}
            animation={false}
            dialogClassName="modal-sm"
        >
            <Modal.Body className={styles.body}>
                <h3>Welcome!</h3>

                <p>
                    mEditor requires that you be an authorized user to add models or
                    edit documents, so please...
                </p>

                <Button onClick={login} variant="link">
                    <MdPerson size={20} />
                    Login
                </Button>

                <small>
                    No account? Please{' '}
                    <a href="https://urs.earthdata.nasa.gov">register</a>.<br />
                    Not sure how to register? View the{' '}
                    <a
                        href={
                            process.env.HELP_DOCUMENT_LOCATION ||
                            '/meditor/docs/user-guide'
                        }
                    >
                        User Guide
                    </a>
                    .
                </small>
            </Modal.Body>
        </Modal>
    )
}

export default LoginDialog

// ui/src/app/auth/components/login-dialog/login-dialog.component.ts
import { Component } from '@angular/core';
import { MatDialogRef } from '@angular/material';

import { environment } from '../../../../environments/environment';

@Component({
	selector: 'med-login-dialog',
	template: `
		<h1 mat-dialog-title>Welcome!</h1>
		<mat-dialog-content>
			The Model Editor requires that you
			be an authorized user to add models
			or edit documents, so please...
			<button mat-button (click)="login()" color="accent" class="login-btn">
				<mat-icon>person</mat-icon>
				Login
			</button>
		</mat-dialog-content>
		<h5> No account? Please <a href="https://urs.earthdata.nasa.gov">register</a></h5>`,
	styles: [
		`
			h1, h5, mat-dialog-content {
				text-align: center;
			}

			h1 {
				font-size: 24px;
			}

			.login-btn {
				margin: 10px 0;
			}
		`
	]
})
export class LoginDialog {

	constructor(
		public dialogRef: MatDialogRef<LoginDialog>
	) {}

	login() {
		window.location.href = environment.API_BASE_PATH + '/login';
	}
}
